CardGenerator/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cards/urls.py
from django.urls import path,include
from .import views

app_name = 'cards'
urlpatterns = [
    path('generateForm',views.generateForm,name='generateForm'),
    path('generate/<int:id>',views.generate,name='generate'),
    path('closead/<int:id>/<int:theme>',views.closead,name='closead'),
    path('form',views.form,name='form'),
    path('download/<int:id>/<int:theme>',views.download,name='download'),
    path('view/<int:id>/<int:theme>',views.view,name='view'),
    
]

home/urls.py
from django.urls import path,include
from .import views

urlpatterns = [
    path('',views.home,name='home'),    
    path('cards', include('cards.urls', namespace='cards')),
    path('user', include('user.urls', namespace='user')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('home',views.home,name='home'),
    path('about',views.about,name='about'),
    path('contact',views.contact,name='contact'),
    path('profile',views.profile,name='profile'),
    path('edit_profile',views.edit_profile,name='edit_profile'),
    path('change_password',views.change_password,name='change_password'),
    path('accounts/', include('allauth.urls')),
       path('social/', include('social_django.urls', namespace='social')),
    path('google/callback', views.google_callback, name='google_callback'),
]

user/urls.py
from django.urls import path,include
from .import views

from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
app_name = 'user'
urlpatterns = [
    path('signup', views.signup,name='signup'),
    path('signin', views.signin,name='signin'),
    path('logout', views.logout_view,name='logout_view'),
     path('verify_email/<str:uidb64>/<str:token>/', views.verify_email, name='verify_email'),
    #  path('password-reset/', PasswordResetView.as_view(template_name='user/password_reset.html'),name='password-reset'),
      path('password-reset/', views.CustomPasswordResetView.as_view(), name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),name='password_reset_complete'),
    
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
import google_auth_oauthlib
from cards.models import Detail
from user.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build
# Create your views here.

def home(request):
    if request.session.get('username'):
        cards = Detail.objects.filter(created_for=User.objects.get(username=request.session['username']))
        return render(request,'home/index.html',{
            'cards':cards
        } )
    return render(request, 'home/index.html')


def contact(request):
    return render(request,'home/contact.html')
def about(request):
    return render(request,'home/about.html')



@login_required(login_url="user:signin")
def profile(request):
    user = User.objects.get(id=request.user.id)
    cards = Detail.objects.filter(created_for=user)
    context = {"user": user,'cards':cards}
    return render(request, "home/profile.html", context)

@login_required(login_url="user:signin")
def edit_profile(request):
    user = User.objects.get(id=request.user.id)
    if request.method == "POST":
        user.name = request.POST.get("name")
        user.phone = request.POST.get("phone")
        user.username = request.POST.get("username")
        user.save()
        return render(request, "home/profile.html", {"user": user, "message": "Profile Updated Successfully"})
    return render(request, "home/edit_profile.html", {"user": user})
        
@login_required(login_url="user:signin")
def change_password(request):
    user = User.objects.get(id=request.user.id)
    if request.method == "POST":
        print(user.password)
        if check_password(request.POST.get("password"),user.password):
            if request.POST.get("new_password") == request.POST.get("repeat_password"):
                user.set_password(request.POST.get("new_password"))
                user.save()
                return render(request, "home/profile.html", {"user": user,"message":"Password Changed Successfully"})
            else:
                return render(request, "home/change_password.html", {"user": user, "message": "Passwords did not match"})
        else:
            return render(request, "home/change_password.html", {"user": user, "message": "Old Password did not match"})
    return render(request, "home/change_password.html", {"user": user})

from django.contrib.auth import login
from django.shortcuts import redirect

def google_callback(request):
    # Exchange the authorization code for a token
    print('shdgf')
    token = google_auth_oauthlib.fetch_token(authorization_response=request.get_full_path())
    
    # Get user information from Google API
    google_api = build('oauth2', 'v2', credentials=token)
    user_info = google_api.userinfo().get().execute()
    
    # Create or retrieve the User object
    user, _ = User.objects.get_or_create(username=user_info['email'])
    request.session['username'] = user.username
    request.session['oauth'] = True
    # Log in the user
    login(request, user)
    return redirect('/')  

templates/home/about.html
{% extends 'home/base.html' %}

{% block content %}
    <h1>About us</h1>
{% endblock %}

templates/home/base.html
<!doctype html>
<html lang="en">
  <head>
  	<title>Infokard</title>
    <meta charset="utf-8">
	{% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.tailwindcss.com"></script>
    
		<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
  </head>

  <style>
    .card{
      font-weight: 300;
      font-size: 20px;
  }

  @media (max-width: 1000px) {
    .card .img{
      display: none;
  }
  .heading{
    display:none
}
  }

  #menu-items {}

  #menu-items a:hover{
    color:  #ccc !important;
  }

  #menu-items a:focus{
    color:  #ccc !important;
  }
  #menu-items a:active{
    color:  #ccc !important;
  }
  #responsive-menu a:hover{
    color:  #ccc !important;
  }
  </style>
  <body>
		
		
        <nav class="bg-dark">
          <div class="max-w-7xl mx-auto px-4">
            <div class="flex items-center justify-between h-16">
              <!-- Logo -->
              <div class="flex-shrink-0">
                <a href="/" class="text-white font-bold text-lg">Infokard</a>
              </div>
              <!-- Mobile Menu Toggle -->
              <div class="md:hidden flex items-center">
                <button id="mobile-menu-toggle" class="text-white hover:text-green-200 focus:outline-none">
                  <i class="fa fa-bars"></i>
                </button>
              </div>
              <!-- Menu Items -->
              <div id="menu-items" class="hidden md:flex justify-end flex-grow">
                <a href="/" style="color:#61BE43;font-size:1rem" class=" hover:text-white px-4">
                  Home
                </a>
                <a href="/profile" style=" color:#61BE43;font-size:1rem" class=" hover:text-white px-4">
                  My Profile
                </a>
                <a href="/contact" style=" color:#61BE43;font-size:1rem" class=" hover:text-white px-4">
                 
                  Contact
                </a>
                {% comment %} <a href="#" class="text-green-300 hover:text-white px-4">
                  <i class="fas fa-envelope mr-1"></i>
                  Contact
                </a> {% endcomment %}
              </div>
              <!-- Login Button -->
              <div class="md:flex-shrink-0 hidden md:block">
                  {% if not request.session.username %}
                  <a href="{% url 'user:signin' %}">	<button type="button" class="btn btn-primary m-2" ><span>Login/Signup</span></button></a>
                    {% else %}
                    <a href="{% url 'user:logout_view' %}">	<button type="button" class="btn btn-primary"><span>logout</span></button></a>
                    {% endif %}	
              </div>
            </div>
            <!-- Responsive Dropdown Menu -->
            <div id="responsive-menu" class="md:hidden hidden">
              <a href="/" style="color:#61BE43;font-size:1rem" class="block py-2 px-4  hover:text-white">
                               Home
              </a>
              <a href="/profile" style="color:#61BE43;font-size:1rem" class="block py-2 px-4  hover:text-white">
                                 My Profile
              </a>
              <a href="/contact" style="color:#61BE43;font-size:1rem" class="block py-2 px-4  hover:text-white">
              
                  Contact
              </a>
            </div>
		
          </div>
        </nav>
        
        <section style="padding:2rem;">
        {% block content %}{% endblock content %}
        </section>
    <script src="{% static 'home/js/jquery.min.js' %}"></script>
    <script src="{% static 'home/js/popper.js' %}"></script>
    <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'home/js/main.js' %}"></script>
    <script>
        // Mobile menu toggle functionality
const mobileMenuToggle = document.getElementById('mobile-menu-toggle');
const menuItems = document.getElementById('menu-items');
const responsiveMenu = document.getElementById('responsive-menu');

mobileMenuToggle.addEventListener('click', () => {
  responsiveMenu.classList.toggle('hidden');
});

// Hide responsive menu when clicking outside
document.addEventListener('click', (event) => {
  const isClickInsideToggle = mobileMenuToggle.contains(event.target);

  if (!isClickInsideToggle) {
    responsiveMenu.classList.add('hidden');
  }
});

// Update menu visibility on window resize
window.addEventListener('resize', () => {
  if (window.innerWidth >= 768) {
    responsiveMenu.classList.add('hidden');
  }
});

    </script>
  </body>
</html>

templates/home/change_password.html
{% extends 'home/base.html' %}
{% load static %}
<style> 
  .password-section {
    background-color: transparent;
  }
</style>
<h3>Change Password</h3>
{% comment %} {% block breadcrum %}

<li class="breadcrumb-item">
  <a href="{% url 'Home' %}">
      <i class="fa-solid fa-house"></i>
  </a>
</li>

<li class="breadcrumb-item">
  <a href="{% url 'profile' %}">
      <i class="fa fa-user"></i>
  </a>
</li>

<li class="breadcrumb-item">
  <a href="{% url 'edit_profile' %}">Edit Profile</a>
</li>

<li class="breadcrumb-item">
  <a href="{% url 'change_password' %}">Change Password</a>
</li>
{% endblock %} {% endcomment %}



{% block content %}
{% if message %}
<div class="container-fluid p-0 m-0">
  <div class="alert-danger alert alert-dismissible m-0 text-center" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="True">&times;</span>
    </button>
     {{ message }}!
  </div>
</div>
<script type="text/javascript">
    setTimeout(function () {
      $('.alert').alert('close');
    }, 4000);
  </script>

{% endif %}

<section class="password-section">
  <form action="{% url 'change_password' %}" method="POST">
    <div class="container col-md-6">
      {% csrf_token %}

      <div class="card mb-4">
        <div class="card-body">

          <center>
            <h3>Change Your Password</h3>
          </center><br>
  
          <div class="form-group row">
            <label for="password" class="col-sm-6 col-form-label"> Old Password</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" name="password" id="password" >
            </div>
        </div>
          <div class="form-group row">
            <label for="password" class="col-sm-6 col-form-label">New Password</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" name="new_password" id="password" >
            </div>
        </div>
          <div class="form-group row">
            <label for="password" class="col-sm-6 col-form-label">Repeat New Password</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" name="repeat_password" id="password" >
            </div>
        </div>

          <div class="text-center">
            <button class="btn btn-dark col-md-4 my-3" type="submit">Change Password</button>
          </div>
        </div>
      </div>


    </div>
  </form>
</section>


{% endblock %}

templates/home/contact.html
{% extends 'home/base.html' %}

{% block content %}
    <h1 class="h3">Contact us at rsvinfo@myrsv.com</h1>
{% endblock %}

templates/home/edit_profile.html
{% extends 'home/base.html' %}
{% load static %}
<style>
    .username-head {
        text-transform: capitalize;
    }
</style>
<h3>Edit Profile</h3>
{% comment %} 
{% block breadcrum %} 
<li class="breadcrumb-item">
    <a href="{% url 'Home' %}">
        <i class="fa-solid fa-house"></i>
    </a>
</li>

<li class="breadcrumb-item">
    <a href="{% url 'profile' %}">
        <i class="fa fa-user"></i>
    </a>
</li>

<li class="breadcrumb-item">
  <a href="{% url 'edit_profile' %}">Edit Profile</a>
</li> {% endcomment %}

{% comment %} {% endblock %} {% endcomment %}


{% block content %}

<div class="container mx-auto">

    {% if message %}
    <div class="container-fluid p-0 m-0">
      <div class="alert-danger alert alert-dismissible m-0 text-center" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="True">&times;</span>
        </button>
         {{ message }}!
      </div>
    </div>
    <script type="text/javascript">
        setTimeout(function () {
          $('.alert').alert('close');
        }, 4000);
      </script>
    
    {% endif %}

    <div class="row">
        <div class="col-lg-4">
            <div class="card mb-4">
                <div class="card-body text-center">
                    <h5 class="username-head my-2">{{ user.name }}</h5>
                    <p class="text-muted mb-2">Membership: {{ user.paid_member }}</p>
                    <div class="row">

                        <div class="col-md-12 d-flex justify-content-center">
{% if request.session.oauth %}
<div class="row">

    <div class="col-md-12 mb-3">
        <a href="https://myaccount.google.com/security"><button type="button" class="btn btn-info btn-lg btn-block">Change
            Password</button></a>
    </div>
{% else %}
                            <div class="row">

                                <div class="col-md-12 mb-3">
                                    <a href="{% url 'change_password' %}"><button type="button" class="btn btn-dark btn-lg btn-block">Change
                                            Password</button></a>
                                </div>
                                {% endif %}
                                {% comment %} <div class="col-md-12 mb-3">
                                    <a href="{% url 'change_phone' %}"><button type="button" class="btn btn-info btn-lg btn-block">Change Mobile No.</button></a>
                                </div> {% endcomment %}
                                {% comment %} <div class="col-md-12">
                                    <a href="{% url 'change_email' %}"><button type="button" class="btn btn-info btn-lg btn-block">Change
                                    Email</button></a>
                                </div> {% endcomment %}
                            </div>
                        </div>

                    </div>
                        <div class="d-flex justify-content-center mb-2">
                            
                        </div>
                        <div class="d-flex justify-content-center mb-2">
                            
                        </div>
                    
                </div>
            </div>
        </div>
        

        <div class="card shadow col-lg-8">
            <form action="" method="post" novalidate>
                {% csrf_token %}

                <div class="form-group row my-3">
                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="name" id="name" value="{{ user.name }}">
                    </div>
                </div>
                <div class="form-group row my-3">
                    <label for="phone" class="col-sm-2 col-form-label">Phone</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="phone" id="phone" value="{{ user.phone }}">
                    </div>
                </div>
                <div class="form-group row my-3">
                    <label for="email" class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-10">
                        <input type="email" class="form-control" name="username" id="email" value="{{ user.username }}">
                    </div>
                </div>

                    <div class="text-center">                    
                        <button class="btn btn-dark col-md-4 my-3" type="submit">Update</button>
                    </div>
                

                
            
            </form>
        </div>
    </div>

</div>

{% endblock %}

templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}


<style>
  h1 {
    font-size: 2.5rem;
    font-weight: 900;
    text-transform: uppercase;
    margin-top: 2em;
    margin-bottom: 0;
}

.text-accent {
    color: #00A1AB;
}

.fs-500 {
    font-size: 1.3125rem;
    margin: 0;
}

.mb {
    margin-bottom: 0.5em;
}

.plans {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
    margin: 2em 0;
}

.plan {
    width: 16.5rem;
    padding: 2em;
    border-radius: 1em;
    margin: 0 0.5em 1em;
}

.plan--light {
    color: #4E4E4E;
    background: linear-gradient(-45deg, #E5E3E8, #FAFAFA);
}

.plan--light .plan-price {
    color: #00A1AB;
}

.plan--light .btn {
    color: #FFF;
    background: #4E4E4E;
}

.plan--accent {
    color: #FFF;
    background: linear-gradient(-45deg, #00A1AB, #3741A0);
}

.plan--accent .btn {
    color: #4E4E4E;
    background: #FFF;
}

.plan-title {
    text-transform: uppercase;
    margin: 0 0 1em;
}

.plan-price {
    margin: 0;
    font-size: 3rem;
    line-height: 1;
    font-weight: 900;
}

.plan-price span {
    display: block;
    font-size: 1.5625rem;
    font-weight: 300;
}

.plan-description {
    margin: 2em 0;
    line-height: 1.5;
}

.btn2 {
    display: inline-block;
    padding: 0.5em 0.5em;
    border-radius: 0.45em;
    text-transform: uppercase;
    text-decoration: none;
    font-weight: 700;
    color: #171717;
    font-size: 1rem;
    background: #f9f9f9;
    border: 2px solid #000;
    transition: 0.3s;
}

.btn2:hover {
    opacity: 0.95;
    color: #29292a;
}

.btn-mb {
  margin: 2em 0;
}

.btn--light {
    color: #4E4E4E;
    background: #61BE43;
}

.btn--dark {
    color: #61BE43;
    background: #4E4E4E;
}

@media (min-width: 1000px) {
    .heading1{
        display:none;
    }
}
.slider-container {
    position: relative;
    width: 100%;
    overflow: hidden;
    padding:1rem;
    border: 2px solid #082970;
  }
  
  .slider {
    display: flex;
    overflow-x: scroll;
    scroll-snap-type: x mandatory;
    scroll-behavior: smooth;
    width: 100%;
  }
  
  .slide {
    flex: 0 0 100%;
    scroll-snap-align: center;
    position: relative;
    display: flex;
    padding:2.5rem;
    justify-content: center;
    align-items: center;

  }
  
  .slide img {
    max-width: 100%;
    max-height: 100%;
    object-fit: contain;
  }
  
  .slide-content {
    position: absolute;
    bottom: 0;
    width: 100%;
    background-color: rgba(0, 0, 0, 0.6);
    color: #fff;
    padding: 20px;
    opacity: 0;
    transition: opacity 0.3s;
  }
  
  .slide:hover .slide-content {
    opacity: 1;
  }
  
  .slide-content h3 {
    font-size: 24px;
    margin-bottom: 10px;
  }
  
  .slide-content p {
    font-size: 16px;
  }
  
  .slider-controls {
    position: absolute;
    bottom: 10px;
    left: 0;
    right: 0;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  
  .slider-control {
    background-color: #333;

    border: none;
    color: #fff;
    font-size: 24px;
    cursor: pointer;
    margin:2rem 10px 0 10px;
    transition: color 0.3s;
  }
  
  .slider-control:hover {
    color: #ccc;
  }
  ::-webkit-scrollbar {
    display: none;
}
  
</style>

<section>
  <div class="card"  style="box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;padding:2rem;margin:2rem;
  background: 019CCA;
  background: linear-gradient(90deg, #61BE43 0%, #61BE43 100%, #61BE43 610%); border-radius:20px;">
  <h3 class="card__title text-dark" style="margin:2rem;font-size:2rem; font-weight:bold">Business Cards</h3>
  <div class="d-flex" style="display: flex;"> 
      <!-- <img width="500px" height="200px" src="https://images.unsplash.com/photo-1571715268998-d6e79bed5fc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=872&q=80" alt=""> -->
      <p style="color: rgb(236, 232, 232);margin:0 2rem;">
          A well-designed business card is crucial for leaving a lasting impression, reflecting professionalism, and differentiating from competitors. It enhances credibility and increases the likelihood of card retention and utilization.
      <a href="{% url 'cards:form' %}"> <button class="btn2   d-flex " style="margin: 5rem auto;" >Generate a Business Card</button> </a></p>
      <img width="400px" class="img" src="{% static 'home/images/wallpaper.png' %}" alt="" />
      
  </div>     
  </div>
  <ul style="list-style-type: none;display:flex;justify-content:space-around;padding:2rem;font-size:1.2rem;">
    <li ><span class="text-dark icon fa fa-address-card-o mx-3"></span>Best Card Designs</li>
    <li><span class="text-dark icon fa fa-share mx-3"></span>Easy Sharing</li>
    <li><span class="text-dark icon fa fa-etsy mx-3"></span>Easy to Use</li>
  </ul>
</section>
<section>
    <h1 class="text-accent text-center">Our Templates</h1>
<div class="slider-container">
    <div class="slider">
      <div class="slide">
        <img src="{% static 'cards/images/view1.png' %}" alt="Design 1">
        
        
      </div>
      <div class="slide">
        <img src="{% static 'cards/images/view2.png' %}" alt="Design 2">
        
        
      </div>
      <div class="slide">
        <img src="{% static 'cards/images/view3.png' %}" alt="Design 3">
        
        
      </div>
      <div class="slide">
        <img src="{% static 'cards/images/view4.png' %}" alt="Design 3">
        
        
      </div>
    </div>
    <div class="slider-controls">
        <button class="slider-control prev" onclick="slidePrev()">&#10094;</button>
        <button class="slider-control next" onclick="slideNext()">&#10095;</button>
      </div>
  </div>
</section>
<section>
  <h1 class="text-accent text-center">Designs</h1>
<p class="fs-500 text-center">Designs that are loved by everyone</p>

<div class="plans">

    <div class="plan plan--light">
        <h2 class="plan-title">basic</h2>

        <img width="150px" src=" {% static 'home/images/cardsample.jpg' %} " alt="">

        <p class="plan-description">
            Eleifend cursus volutpat risus convallis nam sed
            quam sollicitudin eget leo at erat cursus justo
        </p>

        <a   href="{% url 'cards:form' %}" class="btn text-center">Create Now</a>
    </div>

    <div class="plan plan--accent">
        <h2 class="plan-title">Premium</h2>

        <img  width="150px" src=" {% static 'home/images/cardsample2.jpg' %} " alt="">

        <p class="plan-description">
            Eleifend cursus volutpat risus convallis nam sed
            quam sollicitudin eget leo at erat cursus justo
        </p>

        <a   href="{% url 'cards:form' %}" class="btn text-center">Create Now</a>
    </div>

</div>
<div style="display:flex;justify-content:center;margin:0 auto;align-items:center;flex-direction:column">
<p class="fs-500 mb text-center">Need something different? No problem!</p>
<a href="#" class="btn2 btn2-mb">Get in touch</a>
</div>
</section>

</div>

</div>

<script>
    function slideNext() {
        const slider = document.querySelector('.slider');
        slider.scrollBy({ left: slider.offsetWidth, behavior: 'smooth' });
      }
      
      function slidePrev() {
        const slider = document.querySelector('.slider');
        slider.scrollBy({ left: -slider.offsetWidth, behavior: 'smooth' });
      }
</script>

{% endblock content %}

templates/home/profile.html
{% extends 'home/base.html' %}

{% block content %}
{% load static %}
<style>
  .text-muted {
    text-transform: capitalize;
  }
  .user-section {
    background-color: transparent;
  }
</style>

{% comment %} <li class="breadcrumb-item">
  <a href="{% url 'Home' %}">
      <i class="fa-solid fa-house"></i>
  </a>
</li>

<li class="breadcrumb-item">
  <a href="{% url 'profile' %}">
      <i class="fa fa-user"></i>
  </a>
</li> {% endcomment %}
{% if message %}
<div class="container-fluid p-0 m-0">
  <div class="alert-info alert alert-dismissible m-0 text-center" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="True">&times;</span>
    </button>
     {{ message }}!
  </div>
</div>
<script type="text/javascript">
    setTimeout(function () {
      $('.alert').alert('close');
    }, 4000);
  </script>

{% endif %}
<h3 class="h3">Your Profile</h3>

<div class="container">
  <div class="d-flex justify-content-end">
    <a class="btn btn-secondary m-5" href="{% url 'edit_profile' %}"
      >Edit Profile</a
    >
  </div>
</div>

<section class="user-section">
  <div class="container col-sm-12 col-md-6">
    <div class="card mb-4">
      <div class="card-body">
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Name</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">
              {{ user.name }}
            </p>
          </div>
        </div>

        <!-- <hr />

        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Middle Name</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0" style="text-transform: capitalize">
              {{ user.middle_name }}
            </p>
          </div>
        </div>

        <hr />

        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Last Name</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0" style="text-transform: capitalize">
              {{ user.last_name }}
            </p>
          </div>
        </div> -->

        <hr />

        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Phone</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">
              {{ user.phone }}
            </p>
          </div>
        </div>

        <hr />

        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Username</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">
              {{ user.username }}
            </p>
          </div>
        </div>

        <hr />

        {% comment %} <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Email</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{ user.username }}</p>
          </div>
        </div>
        <hr /> {% endcomment %}
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Joined Date</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">
              {{ user.date_joined|date:"d-m-Y" }}
            </p>
          </div>
        </div>
        <hr />
        
       
      </div>
    </div>
  </div>
</section>


<section>
        <h3 class="m-5">Your Previous Designs</h3>
        {% if cards %}
        {% for item in cards %}
    <div class="cards" style="width: 18rem;display:inline-block;margin:1rem;border:0.5px solid;padding:1rem;">
        <img width="150px" class="cards-img-top" src=" {% static 'cards/images/Blue_Black_Modern_For_Business_Card_0VtNhsF.png' %} " alt="Cards image cap">
        <div class="cards-body">
          <h5 class="cards-title">Design {{forloop.counter}}</h5>
          <p class="cards-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="/cardsgenerate/{{item.id}}" class="btn" id="whatsapp" style="background-color: #008445;margin:1rem;color:#fff;margin: 1rem 3rem;">Link {{forloop.counter}} </a>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <p style="margin: 2rem;"> You have not designed any card yet.</p>
       {% endif %}
</section>



{% endblock content %}