CardGenerator/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cards/urls.py
from django.urls import path,include
from .import views

app_name = 'cards'
urlpatterns = [
    path('generateForm',views.generateForm,name='generateForm'),
    path('generate/<int:id>',views.generate,name='generate'),
    path('closead/<int:id>/<int:theme>',views.closead,name='closead'),
    path('form',views.form,name='form'),
    path('download/<int:id>/<int:theme>',views.download,name='download'),
    path('view/<int:id>/<int:theme>',views.view,name='view'),
    
]

home/urls.py
from django.urls import path,include
from .import views

urlpatterns = [
    path('',views.home,name='home'),    
    path('cards', include('cards.urls', namespace='cards')),
    path('user', include('user.urls', namespace='user')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('home',views.home,name='home'),
    path('about',views.about,name='about'),
    path('contact',views.contact,name='contact'),
    path('profile',views.profile,name='profile'),
    path('edit_profile',views.edit_profile,name='edit_profile'),
    path('change_password',views.change_password,name='change_password'),
    path('accounts/', include('allauth.urls')),
       path('social/', include('social_django.urls', namespace='social')),
    path('google/callback', views.google_callback, name='google_callback'),
]

user/urls.py
from django.urls import path,include
from .import views

from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
app_name = 'user'
urlpatterns = [
    path('signup', views.signup,name='signup'),
    path('signin', views.signin,name='signin'),
    path('logout', views.logout_view,name='logout_view'),
     path('verify_email/<str:uidb64>/<str:token>/', views.verify_email, name='verify_email'),
    #  path('password-reset/', PasswordResetView.as_view(template_name='user/password_reset.html'),name='password-reset'),
      path('password-reset/', views.CustomPasswordResetView.as_view(), name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),name='password_reset_complete'),
    
]

cards/models.py
from django.db import models
from CardGenerator.settings import AUTH_USER_MODEL

# Create your models here.
class Detail(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    role = models.CharField(max_length=100)
    profileimage  = models.ImageField(upload_to='images/')
    phone = models.CharField(max_length=100)
    companyname = models.CharField(max_length=100)
    companylogo = models.ImageField(upload_to='images/')
    website = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    
    created_at = models.DateTimeField(auto_now_add=True)
    created_for = models.ForeignKey(AUTH_USER_MODEL,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name + " " + self.companyname

cards/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from user.models import User
from django.urls import reverse
from . models import Detail
from django.contrib import messages
from bs4 import BeautifulSoup
# Create your views here.

def generateForm(request):
    if request.session.get('username') and request.method == 'POST' :
        name = request.POST['name']
        profileimage = request.FILES['profileimage']
        email = request.POST['email']
        role = request.POST['role']
        phone = request.POST['phone']
        companyname = request.POST['companyname']
        companylogo = request.FILES['logo']
        website = request.POST['website']   
        address = request.POST['address']
        created_for = User.objects.get(username=request.session['username'])
        details = Detail(name=name,email=email,role=role,phone=phone,profileimage = profileimage,companyname=companyname,companylogo=companylogo,website=website,address=address,created_for=created_for)
        details.save()
        print(details.id)
            # return view(request=request,id=details.id,theme=1)
        messages.success(request,'Card Generated Successfully')
        
        return render(request,'cards/generate.html',{'message' : "Card Generated Successfully",'details':details,'username':name,'id':details.id,})
    else:
        return render(request,'user/signin.html',{'message' : "You need to sigin to generate Cards"})
    
    
def generate(request,id):
    if request.session.get('username') and request.method == 'GET':
        details = Detail.objects.get(id = id)
        messages.success(request,'Card Generated Successfully')
        return render(request,'cards/generate.html',{'message' : "Card Generated Successfully",'details':details,'username':details.name,'id':details.id,})
    return render(request,'user/signin.html',{"message":"You need to sigin to generate Cards"})


def form(req):
    if req.session.get('username',None)==None:
        return render(req,'user/signin.html',{'message' : "You need to sigin to generate Cards"})
    return render(req,'cards/form.html')


def view(req,id,theme):
    details = Detail.objects.get(id=id)
    username = details.name
    # user = User.objects.get(username=req.session['username'])
    # print(user)
    # if theme >2 and theme <10:
        # if user.paid_member==True:
        #     return render(req,'cards/card'+str(theme)+'.html',{'username':username,'details':details,'id':id,'theme':theme})
        # else:
        #     messages.error(req,'You need to be a paid member to use this theme')
            # return redirect('payment:process_payment')
    return render(req,'cards/card'+str(theme)+'.html',{'details':details,'id':id,'theme':theme})

def download(req,id,theme):
    details = Detail.objects.get(id=id)
    if 'username' in req.session:
        user = User.objects.get(username=req.session['username'])
        if user.paid_member == False:
            return redirect('payment:process_payment')
        return render(req,'cards/card'+str(theme)+'.html',{'details':details,'id':id,'theme':theme,"paidmember":user.paid_member})
    return render(req,'cards/card'+str(theme)+'.html',{'details':details,'id':id,'theme':theme,"alert":"You need to sign in to download the card"})

def closead(req,id,theme):
    details = Detail.objects.get(id=id)
    if 'username' in req.session:
        user = User.objects.get(username=req.session['username'])
        if user.paid_member == False:
            return redirect('payment:process_payment')
        return render(req,'cards/card'+str(theme)+'.html',{'details':details,'id':id,'theme':theme,"paidmember":user.paid_member})
    return redirect('user:signin')

templates/cards/base.html
<!doctype html>
<html lang="en">
  <head>
  	<title>Infokard</title>
    <meta charset="utf-8">
	{% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Include html2canvas library -->
<script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dom-to-image/2.6.0/dom-to-image.min.js" integrity="sha512-01CJ9/g7e8cUmY0DFTMcUw/ikS799FHiOA0eyHsUWfOetgbx/t6oV4otQ5zXKQyIrQGTHSmRVPIgrgLcZi/WMA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.rawgit.com/tsayen/dom-to-image/bfc00a6c5bba731027820199acd7b0a6e92149d8/dist/dom-to-image.min.js"></script>
    <script type="text/javascript" src="https://cdn.rawgit.com/davidshimjs/qrcodejs/gh-pages/qrcode.min.js"></script>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
  </head>

  <style>
    .card{
      font-weight: 300;
      font-size: 20px;;
  }

  @media (max-width: 1000px) {
    .card img{
      display: none;
  }
  }
  
  </style>
  <body>
		{% block sidebar %}
		<div class="wrapper d-flex align-items-stretch">
			<nav id="sidebar" class="active">
				<h1><a href="/" class="logo">{{username}}</a></h1>
        <ul class="list-unstyled components mb-5">
          <li class="active">
            <a href="/"><span class="fa fa-home"></span> <img src="" alt=""></a>
          </li>
          <li>
              <a href="/about"><span class="fa fa-user"></span> <img src="" alt=""></a>
          </li>
          <li>
            <a href="/"><span class="fa fa-sticky-note"></span> <img src="" alt=""></a>
          </li>
          <li>
            <a href="#"><span class="fa fa-cogs"></span> <img src="" alt=""></a>
          </li>
          <li>
            <a href="/contact"><span class="fa fa-paper-plane"></span> <img src="" alt=""></a>
          </li>
        </ul>
        {% endblock %}

        <div class="footer">
        	<p>
					  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
					</p>
        </div>
    	</nav>

        <!-- Page Content  -->
      <div id="content" class="p-4 p-md-5">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">

            <button type="button" id="sidebarCollapse" class="btn btn-primary">
              <i class="fa fa-bars"></i>
              <span class="sr-only">Toggle Menu</span>
            </button>
            <h4 class="text-primary heading">Choose any template</h4>
            <div class="" id="navbarSupportedContent">
              <ul class="nav navbar-nav ml-auto">
                <li class="nav-item active">
					<form class="navbar-form form-inline ml-auto">
						{% if not request.session.username %}
					<a href="{% url 'user:signup' %}">	<button type="button" class="btn btn-primary m-2" ><span>Login/Signup</span></button></a>
						{% else %}
						<a href="{% url 'user:logout' %}">	<button type="button" class="btn btn-primary"><span>logout</span></button></a>
						{% endif %}	
					</form>	
                </li>
                {% comment %} <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Portfolio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li> {% endcomment %}
              </ul>
            </div>
          </div>
        </nav>

        {% block content %}{% endblock content %}

    <script src="{% static 'home/js/jquery.min.js' %}"></script>
    <script src="{% static 'home/js/popper.js' %}"></script>
    <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'home/js/main.js' %}"></script>
  </body>
</html>

templates/cards/card2.html
<!DOCTYPE html>
{% load static %}
<html  lang="en" class="notranslate" translate="no">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Template 2</title>
<!-- FONTS ONLINE -->
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300italic,400italic,600,600italic,700,700italic,800,800italic,300' rel='stylesheet' type='text/css'>

<!--MAIN STYLE-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link href=" {% static 'cards/card1/css/font.css' %} " rel="stylesheet" type="text/css">
<link href=" {% static 'cards/card1/css/fontello.css' %} " rel="stylesheet" type="text/css">
<link href=" {% static 'cards/card1/css/base.css' %} " rel="stylesheet" type="text/css">
<link href=" {% static 'cards/card1/css/skeleton.css' %} " rel="stylesheet" type="text/css">
<link href=" {% static 'cards/card1/css/main.css' %} " rel="stylesheet" type="text/css">
<link href=" {% static 'cards/card1/css/magnific-popup.css' %} " rel="stylesheet"  />

<link href=" {% static 'cards/card2/css/animate.css' %} " rel="stylesheet" type="text/css">
<link href=" {% static 'cards/card2/css/bootstrap.min.css' %} " rel="stylesheet" type="text/css">
<link href=" {% static 'cards/card2/css/font-awesome.min.css' %} " rel="stylesheet" type="text/css">
<link href=" {% static 'cards/card2/css/main.css' %} " rel="stylesheet" type="text/css">
<link href=" {% static 'cards/card2/css/style.css' %} " rel="stylesheet" type="text/css">
<link href=" {% static 'cards/card2/css/responsive.css' %} " rel="stylesheet" type="text/css">


<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

</head>
<body>

<!-- Page Wrap -->
<div id="wrap"> 
  
  <!-- Menu Link -->
  <div class="nav-menu"> <a href="#." class="cd-bouncy-nav-trigger"><i class="ion-navicon"></i></a> </div>
  
  <!-- Menu Overlay -->
  <div class="cd-bouncy-nav-modal">
    <nav>
      <ul class="cd-bouncy-nav">
        <li><a href="{% url 'cards:generate' id %}"><i class="ion-ios-home"></i> GoBack</a></li>
        <li><a href="#contact"><i class="ion-paper-airplane"></i> Contact</a></li>
      </ul>
    </nav>
    <a href="#." class="cd-close">Close modal</a> </div>
    

    <!-- Profile -->
  <div class="profile animated bounceInUp"  id="main-container" >
    <div class="container">
      <div class="profile-in">
      
      <!-- Avatar -->
        <div class="text-center">
          <div class="avatar"> 
            <img  width="350px" class="images" src="/media/{{details.profileimage}}"> </div>
        </div>
        <h1>Hello, I am <strong style="color:#fff">{{details.name}}</strong> Passionate <span>{{details.role}}</span></h1>
        <hr>
        <p>Mobile Number : <span style="color:red" >{{details.phone}} </span> </p>
        <p>Email : <span style="color:red" >{{details.email}} </span> </p>
        <p style="display:inline-block">company : <span style="color:red" >{{details.companyname}} </span> </p>
        <img style="display:inline-block" width="100px" src="/media/{{details.companylogo}}"> 
        <p>Webiste : <span style="color:red" >{{details.website}} </span> </p>
        <p>Address : <span style="color:red" >{{details.address}}</ </span> <p>
          <div class="aboutSocial">
            <p>Share Now : </p>
            <ul>
                <li><a href="#" id="twitter" target="_blank"><i class="icon-twitter"></i></a></li>
                <li><a href="#" id="facebook" target="_blank"><i class="icon-facebook"></i></a></li>
                <li><a href="#" id="linkedin" target="_blank"><i class="icon-linkedin"></i></a></li>
                <li><a href="#" id="whatsapp" target="_blank"><i class="icon-w">W</i></a></li>
                <br> <br>
                <button  class="btn btn-primary regButton share-btn" onclick="showButtons()" style="background-color: rgb(6, 144, 208);cursor:pointer;color:aliceblue;margin-bottom:2rem;">Share </button> <br>
                <button class="btn btn-primary regButton download-btn" onclick="downloadPage()" style="background-color: rgb(6, 144, 208);cursor:pointer;color:aliceblue;margin-bottom:2rem;">Download</button> <br>
                <li><img src="" style="width: 10.2rem"  alt="QR Code" id="qr"></li>
            </ul>
            <br>
          </div>
      </div>
    </div>
    
  </div>
  
</div>


<section id="contact" style="background:#fff;" class="offset section">


  <!--Inner content-->
  <div class="innerContent">

  <!--Container-->
  <div class="container clearfix">

    <div class="sixteen columns">
    <h1 class="titleBig">contact</h1>
    </div>

  

      <div class="sixteen columns contactForm">
        <p>You can send a message to  me</p>

        <div class="cForm">
        <form method="post" enctype="text/plain" action="mailto:someone@example.com">


          <p>
          <label for="name">Name <span class="required">*</span></label>
              <input type="text" name="name" id="name">
          </p>

          <p>
          <label for="email">Email <span class="required">*</span></label>
              <input type="text" name="email" id="email">
          </p>


            <p>
            <label for="subject">Subject</label>
                <input type="text" name="subject" id="subject">
            </p>




            <p>
            <label for="subject">Message <span class="required">*</span></label>
       <textarea name="message" id="message" cols="45" rows="10"></textarea>
      </p>
              <div class="fBtn"><button id="submit" class="regButton"><i class="icon-paper-plane"></i>Send message</button></div>
            </form>
        <div id="success"><h2>Your message has been sent. Thank you!</h2></div>
        <div id="error"><h2>Sorry your message can not be sent.</h2></div>


      </div>			


      </div>




      </div>
      <!--End container-->


    </div>
    <!--End inner content-->

    </section>

      <!--End contact section-->
      
      

  <!--Footer-->				
    <footer class="footer text-white offset" >

      <!--Bottom footer-->
      <div class="footerholder" >
          <!--Container-->
          <div class="container clearfix">

            <div class="eight columns">

              <p style="color:#fff">Thank you</p>
            </div>


              <div class="eight columns ">
            <ul class="socialsFooter">
              <li><a href="#" id="twitter2" target="_blank"><i class="icon-twitter"></i></a></li>
															<li><a href="#" id="facebook2" target="_blank"><i class="icon-facebook"></i></a></li>
															<li><a href="#" id="linkedin2" target="_blank"><i class="icon-linkedin"></i></a></li>
															<li><a href="#" id="whatsapp2" target="_blank"><i class="icon-w">W</i></a></li>


            </ul>

              </div>

      </div>
        <!--End container-->
      </div>
        <!--End bottom footer-->


    </footer>

<!--End footer-->

    


</div>
<!--ENd wrapper-->





<!-- Wrap End --> 

<script src=" {% static 'cards/card2/js/jquery-1.11.0.min.js' %} "></script> 
<script src=" {% static 'cards/card2/js/bootstrap.min.js' %}"></script> 
<script src=" {% static 'cards/card2/js/counter.js' %} "></script> 
<script src=" {% static 'cards/card2/js/jquery.prettyPhoto.js' %} "></script> 
<script src=" {% static 'cards/card2/js/main.js' %} "></script>
<script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>
<script>
	document.getElementById("qr").src = "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data="+window.location.href;
	document.getElementById("twitter").href = `https://twitter.com/intent/tweet?url=${window.location.href}&text='My Profile'`;
	document.getElementById("facebook").href = `https://www.facebook.com/sharer/sharer.php?u=${window.location.href}`;
	document.getElementById("linkedin").href = `https://www.linkedin.com/sharing/share-offsite/?url=${window.location.href}`;
	document.getElementById("whatsapp").href = `https://api.whatsapp.com/send?text=${window.location.href}`;
	
	document.getElementById("twitter2").href = `https://twitter.com/intent/tweet?url=${window.location.href}&text='My Profile'`;
	document.getElementById("facebook2").href = `https://www.facebook.com/sharer/sharer.php?u=${window.location.href}`;
	document.getElementById("linkedin2").href = `https://www.linkedin.com/sharing/share-offsite/?url=${window.location.href}`;
	document.getElementById("whatsapp2").href = `https://api.whatsapp.com/send?text=${window.location.href}`;
  

	var buttonContainer = null;
	function showButtons() {
		// Create buttons
		if (!buttonContainer) {
		  // Create the button container
		  buttonContainer = document.createElement('div');
		  buttonContainer.classList.add('button-container');
	
		  // Create buttons
		  var copyButton = createButton('Copy URL', 'btn-primary');
		  var whatsappButton = createButton('Share on WhatsApp', 'btn-success');
		  var instagramButton = createButton('Share on Instagram', 'btn-danger');
      copyButton.style.backgroundColor = "#E2F6CA";
      whatsappButton.style.backgroundColor = "#A2FF86";
      instagramButton.style.backgroundColor = "#FF90BB";
		  // Append buttons to the container
		  buttonContainer.appendChild(copyButton);
		  buttonContainer.appendChild(whatsappButton);
		  buttonContainer.appendChild(instagramButton);
	
		  // Append the button container to the document body
			  
		  // Append the container after the "Share" button
		  var shareButton = document.querySelector('.share-btn');
		  shareButton.insertAdjacentElement('afterend', buttonContainer);
			
	
		  copyButton.addEventListener('click', function () {
			copyUrlToClipboard(window.location.href);
		  });
	
		  whatsappButton.addEventListener('click', function () {
			shareOnWhatsApp(window.location.href);
		  });
	
		  instagramButton.addEventListener('click', function () {
			shareOnInstagram(window.location.href);
		  });
		}
		else{
		  buttonContainer.classList.toggle('hidden');
	  }
	}
	
	  function createButton(text, className) {
		var button = document.createElement('button');
		button.innerText = text;
		button.classList.add('btn', className);
		return button;
	  }
	  function copyUrlToClipboard(url) {
		// Copy the URL to the clipboard
		navigator.clipboard.writeText(url)
		  .then(() => {
			alert('URL copied to clipboard');
		  })
		  .catch(error => {
			console.error('Failed to copy URL to clipboard', error);
		  });
	  }
	  
	  function shareOnWhatsApp(url) {
		// Open WhatsApp with the image URL
		window.open('https://api.whatsapp.com/send?text=' + encodeURIComponent(url));
	  }
	  
	  function shareOnInstagram(url) {
		// Open Instagram with the image URL
		window.open('https://www.instagram.com/share?url=' + encodeURIComponent(url));
	  }
	  
	  function downloadPage() {
      // Use html2canvas to capture the page as an image
      let main_content=document.getElementById("main-container")

      main_content.classList.add("card-download")
      document.getElementsByClassName("aboutSocial")[0].style.display="none";
      html2canvas(main_content).then(function(canvas) {
        // Convert the canvas to a data URL
        var image = canvas.toDataURL();
    
        // Create an anchor element
        var anchor = document.createElement('a');
        anchor.href = image;
        anchor.download = 'profile.png';
    
        // Trigger the download
        anchor.click();
      });
      main_content.classList.remove("card-download")
      document.getElementsByClassName("aboutSocial")[0].style.display="block";
      }
	  
</script>
</body>
</html>

templates/cards/form.html
{% extends 'home/base.html' %}

{% block content %}

{% load static %}

<style>
    @media (max-width: 850px) {
        .container-flex{
            display: flex;
            flex-direction: column;
        }
        .button{
            width: 50% !important;
        }
    }
</style>
<div class="container">
    <form action=" {% url 'cards:generateForm' %} " method="post"  enctype="multipart/form-data">
        {% csrf_token %}
      <div class="container-flex" style="display: flex;flex-direction:column;justify-content:space-around;">
        <div>
        <h2 class="h4 mt-2">Enter Your Details : </h2>
       
        <div class="form-group">
            <label for="lname"> Name</label>
            <input type="text" class="form-control" id="name" required
                placeholder="Enter your name" name="name">
        </div>
        <div class="form-group">
            <label for="email"> Email Id:</label>
            <input type="email" class="form-control" id="email" required
                placeholder="Enter your Email Id" name="email">
        </div>
        <div class="form-group">
            <label for="email"> Your Role :</label>
            <input type="text" class="form-control" id="role" required
                placeholder="Enter your role " name="role">
        </div>
        <div class="form-group">
            <label for="phone"> Phone No:</label>
            <input type="text" class="form-control" id="phone" required
                placeholder="Enter Phone Number" name="phone">
        </div>
        <div class="form-group">
            <label for="profileimage">Profile Image :</label>
            <div class="mb-3">
                <input class="form-control" name="profileimage" required type="file" id="formFile">
              </div>
        </div>
    
  
       
        <!-- <div class="form-group form-check">
            <label class="form-check-label">
                <input class="form-check-input" type="checkbox"
                    name="remember">
                    Remember me
            </label>
        </div> -->
        <!-- <label for="theme">Card Theme</label>
        <div class="form-check" style="padding:1.5rem">
            <input class="form-check-input" style="cursor:pointer" type="radio" value="1" name="theme" id="flexRadioDefault1" checked>
            <label class="form-check-label" style="cursor:pointer" for="flexRadioDefault1">
             Theme 1
             <img  src="{% static 'cards/images/card1.png' %}" alt="" width="200px" height="100px">
            </label>
          
          </div>
          <div class="form-check">
            <input class="form-check-input" style="cursor:pointer" type="radio" name="theme" value="2" id="flexRadioDefault2" >
            <label class="form-check-label" style="cursor:pointer" for="flexRadioDefault2">
              Theme 2
              <img src="{% static 'cards/images/card2.png' %}" alt="" width="200px" height="100px">
            </label> -->
           
          <!-- </div> -->
        <!-- </div> -->
       </div> 
    <div>
        <h2 class="h4 mt-2">Enter The Company Details : </h2>
        <div class="form-group">
            <label for="lname">Company Name</label>
            <input type="text" class="form-control" id="lname" required
                placeholder="Enter company name" name="companyname">
        </div>
        <div class="form-group">
            <label for="contact">Company Logo:</label>
            <div class="mb-3">
                <input class="form-control" name="logo" required type="file" id="formFile">
              </div>
        </div>
        <div class="form-group">
            <label for="contact">Company Webiste:</label>
            <input type="text" class="form-control" id="contact" 
                placeholder="Enter Company Website" name="website">
        </div>
        <div class="form-group">
            <label for="contact">Address:</label>
            <input type="text" class="form-control" id="contact" 
                placeholder="Enter Company Address" name="address">
        </div>
    </div>
 </div>
 <div style="display: flex;justify-content:center;">
    <button type="submit" class="btn bg-dark p-2 text-light m-5 button" style="width: 15%;">
        Submit
    </button>
    </div>
    </form>
</div>

{% endblock content %}