CardGenerator/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path,include
from .import views

urlpatterns = [
    path('',views.home,name='home'),    
    path('cards', include('cards.urls', namespace='cards')),
    path('user', include('user.urls', namespace='user')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('home',views.home,name='home'),
    path('about',views.about,name='about'),
    path('contact',views.contact,name='contact'),
    path('profile',views.profile,name='profile'),
    path('edit_profile',views.edit_profile,name='edit_profile'),
    path('change_password',views.change_password,name='change_password'),
    path('accounts/', include('allauth.urls')),
       path('social/', include('social_django.urls', namespace='social')),
    path('google/callback', views.google_callback, name='google_callback'),
]

user/urls.py
from django.urls import path,include
from .import views

from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
app_name = 'user'
urlpatterns = [
    path('signup', views.signup,name='signup'),
    path('signin', views.signin,name='signin'),
    path('logout', views.logout_view,name='logout_view'),
     path('verify_email/<str:uidb64>/<str:token>/', views.verify_email, name='verify_email'),
    #  path('password-reset/', PasswordResetView.as_view(template_name='user/password_reset.html'),name='password-reset'),
      path('password-reset/', views.CustomPasswordResetView.as_view(), name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),name='password_reset_complete'),
    
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    name = models.CharField(max_length=50, default='Anonymous')
    phone  = models.CharField(max_length=20, default='0000000000')
    paid_member = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    

user/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .models import User
from cards.models import Detail
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail
from CardGenerator import settings
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
# Create your views here.
def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        name = request.POST['name']
        phone = request.POST['phone']
        password = request.POST['password']
        # if password != confirm_password:
        #     return render(request,'user/signup.html',{'message':'Password does not match'})
        if User.objects.filter(username = username).exists():
             return render(request,'user/signin.html',{'message':'User already exists with that username Please sign in'})
        user = User.objects.create_user(username = username, password = password,name=name,phone=phone)
        user.is_active = False
        user.email = username
        token = default_token_generator.make_token(user)

        # Build verification URL
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        verification_url = request.build_absolute_uri('/userverify_email/{}/{}/'.format(uid, token))
        subject =  ''' Welcome to Infokard Card Generator, Verify your account'''
        message =  '''
        Hello {},
                Welcome to Card Generator, the ultimate platform for designing business cards! We're thrilled to have you on board as a new user. With our easy-to-use interface and powerful design tools, you'll be able to create stunning business cards.

                Get started by logging into your account and exploring the wide range of customizable templates we offer. Whether you're looking for a sleek and professional design or something more creative and unique, we have options to suit every style.

                Customize your business card with your logo, contact information, and a brief description of your services or expertise. Our intuitive editor allows you to adjust fonts, colors, and layouts, ensuring your business card perfectly represents your brand.

                Once you're satisfied with your design, simply save it and share high-quality printed cards right from our site. 

                If you have any questions or need assistance along the way, our friendly support team is here to help. Enjoy your journey with Card Generator, and we can't wait to see the fantastic business cards you create
                Please click on the link below to verify your email address and complete the registration of your account:\n\n{}\n\nThank you for using our site!\n\Infokard Team'''.format(user.name, verification_url)
        email_from = settings.EMAIL_HOST_USER
        # send_mail(subject, message, email_from, [username,])


        # Prepare email message
        # subject = 'Welcome to Card Generator'
        # message = "Hi {},\n\nWelcome to Card Generator! Please click on the link below to verify your email address and complete the registration of your account:\n\n{}\n\nThank you for using our site!\n\nCard Generator Team".format(user.username, verification_url)
        # email_from = settings.EMAIL_HOST_USER
        send_mail(subject, message, email_from, [username, ])
        user.save()
        return render(request, 'user/signin.html', {'message': 'User created successfully. Please check your email for verification instructions.'})
    
        
        
    return render(request,'user/signup.html')

def verify_email(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
        if default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            return render(request, 'user/verification_success.html')
        else:
            return render(request, 'user/verification_failure.html')
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        return render(request, 'user/verification_failure.html')

def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        # Check if the user exists
        if not User.objects.filter(username=username).exists():
            return render(request, 'user/signup.html', {'message': "User doesn't exist. Please sign up"})
        
        user = User.objects.get(username=username)
        
        # Check if the user account is verified
        if not user.is_active:
            return render(request, 'user/signin.html', {'message': 'User account is not verified yet. Please check your email for verification instructions.'})
        
        # Authenticate the user with credentials
        authenticated_user = authenticate(username=username, password=password)
        
        if authenticated_user is not None:
            if authenticated_user.is_active:
                request.session['username'] = username
                request.session.save()
                login(request, authenticated_user)
                return redirect('/')
        
        return render(request, 'user/signin.html', {'message': 'Incorrect username or password'})
    
    return render(request, 'user/signin.html')

def logout_view(request):
    
    del request.session['username']
    request.session.save()
    logout(request)
    return render(request,'user/signin.html',{'message':'Logged out successfully'})


from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.urls import reverse_lazy

class CustomPasswordResetView(PasswordResetView):
    template_name = 'user/password_reset.html'
    success_url = reverse_lazy('user:password_reset_done')  # Update the URL name
    email_template_name = 'user/reset_password.html'
    extra_email_context = {'protocol': 'http', 'domain':'businesscardgenerator-production.up.railway.app'}
    
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.forms import SetPasswordForm
from django.urls import reverse_lazy

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'user/password_reset_confirm.html'
    success_url = reverse_lazy('user:password_reset_complete')
    form_class = SetPasswordForm

templates/user/password_reset.html
{%extends 'home/base.html'%}

{%block content%}
<div class="center" style="padding:2rem;">
	<style>
		input{
			border: 2px solid #ccc;
		}
	</style>
	<form method="post" class="card" style="padding:2rem">
		{% csrf_token %}
	    <h2 class="text-center">Reset Password</h2>
		{% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
		<div class="form-buttons mt-5">
			<input type="submit" value="Send" class="btn btn-primary">
			<a href="{%url 'user:signin' %}"  class="btn btn-outline">Cancel</a>
		</div>
	</form>
	</div>
{%endblock content%}

templates/user/password_reset_complete.html
{%extends 'home/base.html'%}

{%block content%}

<div class="card center">
	<p>Your password has been changed successfully. Please <a href="{% url 'user:signin' %}" style="color:blue;text-decoration:underline;">Login</a></p>
</div>
 	
{%endblock content%}

templates/user/password_reset_confirm.html
{%extends 'home/base.html'%}

{%block content%}

<div class="center">
	<style>
		input{
			border: 2px solid #ccc;
		}
	</style>
	<form method="post" class="card" style="padding:2rem;">
	  {% csrf_token %}
	  <h2>Password Reset Confirm</h2>
	  
	  {% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
	  
	  
	  <div class="mt-5">
	    <button type="submit" class="btn btn-primary">Reset Password</button>
	  </div>
	</form>
</div>


{%endblock content%}

templates/user/password_reset_done.html
{%extends 'home/base.html'%}

{%block content%}

<div class="center card">
	<h2>Reset Password</h2>
	<p>Please check your inbox and follow the instruction to reset your password.</p>
</div>

{%endblock content%}

templates/user/reset_password.html
{% load i18n %}

{% autoescape off %}
Dear {{ user.get_username }},

You have requested to reset your password for your account at Card Generator.

Please click on the following link to reset your password:

{{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}

If you didn't request this, please ignore this email.

Sincerely,
Card Generator Team
{% endautoescape %}

templates/user/signin.html
<!DOCTYPE html>
<html>
	<head>
		{% load static %}
		{% load socialaccount %}
		<meta charset="utf-8">
		<title>Login Here</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- STYLE CSS -->
		<link rel="stylesheet" href="{% static 'user/css/style.css' %}">
		<style>
			.google-btn {
				width: 100%;
				margin: 2rem auto;
				text-align: center;
			}
			.google-btn button {
				width: 184px;
				height: 42px;
				background-color: #4285f4;
				border-radius: 2px;
				box-shadow: 0 3px 4px 0 rgba(0, 0, 0, .25);
				border: none;
				color: #fff;
				font-size: 14px;
				letter-spacing: 0.2px;
				font-family: "Roboto";
			}
			.google-btn button:hover {
				box-shadow: 0 0 6px #4285f4;
			}
			.google-btn button:active {
				background: #1669f2;
			}
			.forgot-pass {
				width: 100%;
				margin: 2rem auto;
				text-align: center;
			}
			.forgot-pass button {
				width: 184px;
				height: 42px;
				background-color: #4285f4;
				border-radius: 2px;
				box-shadow: 0 3px 4px 0 rgba(0, 0, 0, .25);
				border: none;
				color: #fff;
				font-size: 14px;
				letter-spacing: 0.2px;
				font-family: "Roboto";
			}
			.forgot-pass button:hover {
				box-shadow: 0 0 6px #4285f4;
			}
			.forgot-pass button:active {
				background: #1669f2;
			}
		</style>
	</head>

	<body>

		<div class="wrapper">
			<div class="inner">
				<div class="image-holder">
					<img src="https://plus.unsplash.com/premium_photo-1682148400830-e400005b5382?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=388&q=80" alt="">
				</div>
				<form style="display: none;" method="POST" id="oauth-form" action="{% url 'social:begin' 'google-oauth2' %}">
					{% csrf_token %}
					</form>
				<form  action="{% url 'user:signin' %}" method="POST">
					<h3>Sign In</h3>
					{% csrf_token %}
					{% if message %} 
						<p class="hint-text text-center" style="color:#FF0000">{{message}}</p>
					{% endif %}
					<div class="form-holder active">
						<input type="email" class="form-control" name="username" placeholder="email" required="required">
					</div>
					<div class="form-holder">
						<input type="password" placeholder="Password" name="password" class="form-control" style="font-size: 15px;">
					</div>
					<div class="checkbox">
						<label>
							<input type="checkbox" checked> I agree all statement in <a href="#">Terms & Conditions</a>
							<span class="checkmark"></span>
						</label>
					</div>
					<div class="form-login">
						<button>Sign In</button>
						<p>Don't Have an account? <a href="{% url 'user:signup' %}">Signup</a></p>
						
					</div>
					<div class="forgot-pass">
						Forgot Password? <a href="{% url 'user:password-reset' %}">Click Here</a>
				</div>
					{% comment %} <div class="google-btn">
							<button type="submit">Sign in with Google</button>
				
					</div> {% endcomment %}
				</form>
			</div>
		</div>

		<script src="{% static 'user/js/jquery-3.3.1.min.js' %}"></script>
		<script src="{% static 'user/js/main.js' %}"></script>
		<script>
			document.querySelector('.google-btn button').addEventListener('click', function(event) {
				event.preventDefault(); 
				document.querySelector('#oauth-form').submit();
			});
		</script>
	</body>
	<!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

templates/user/signup.html
<!DOCTYPE html>
<html>
	<head>
		{% load static %}
		<meta charset="utf-8">
		<title>Signup Here</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- STYLE CSS -->
		<link rel="stylesheet" href="{% static 'user/css/style.css' %}">
		
	</head>

	<body>

		<div class="wrapper">
			<div class="inner">
				<div class="image-holder">
					<img  src="https://plus.unsplash.com/premium_photo-1682148400830-e400005b5382?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=388&q=80" alt="">
				</div>
				<form action="{% url 'user:signup' %}" method="POST">
					<h3>Sign Up</h3>
					{% csrf_token %}
					{% if message %} 
					<p class="hint-text text-danger">{{message}}</p>
					{% endif %}
					<div class="form-holder active">
						<input type="email	" class="form-control" name="username" placeholder="Email" required="required">
					</div>
					<div class="form-holder ">
						<input type="text	" class="form-control" name="name" placeholder="Name" required="required">
					</div>
					<div class="form-holder ">
						<input type="text	" class="form-control" name="phone" placeholder="Phone Number" required="required">
					</div>
					<div class="form-holder">
						<input type="password" placeholder="Password" name="password" class="form-control" style="font-size: 15px;">
					</div>
					<div class="checkbox">
						<label>
							<input type="checkbox" checked> I agree all statement in <a href="#">Terms & Conditions</a>
							<span class="checkmark"></span>
						</label>
					</div>
					<div class="form-login">
						<button>Sign up</button>
						<p>Already Have account? <a href="{% url 'user:signin' %}">Login</a></p>
					</div>
				</form>
			</div>
		</div>

		<script src=" {% static 'user/js/jquery-3.3.1.min.js' %} "></script>
		<script src=" {% static 'user/js/main.js' %} "></script>
	</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

templates/user/verification_failure.html
{% extends 'home/base.html' %}

{% block title %}Email Verification Failure{% endblock %}

{% block content %}
  <div class="container">
    <div class="verification-message">
      <h2>Email Verification Failed</h2>
      <p>Sorry, the email verification link is invalid or has expired.</p>
      <p>Please contact support for further assistance.</p>
    </div>
  </div>
{% endblock %}

templates/user/verification_success.html
{% extends 'home/base.html' %}

{% block title %}Email Verification Success{% endblock %}

{% block content %}
  <div class="container">
    <div class="verification-message">
      <h2>Email Verification Successful</h2>
      <p>Your email has been successfully verified. You can now log in to your account.</p>
      <a href="{% url 'user:signin' %}" class="btn btn-primary">Sign In</a>
    </div>
  </div>
{% endblock %}